name: go_logistics_driver
description: "Join GoRider to earn by delivering parcels quickly and efficiently to clients."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+4

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.4.0
  dotted_line: ^3.2.3
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.3
  pinput: ^3.0.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.0
  fl_chart: ^0.69.0
  get_it: ^7.2.0
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_google_maps_webservices: ^1.1.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  intl_phone_field: ^3.1.0
  flutter_polyline_points: ^2.1.0
  flutter_ringtone_player:
  permission_handler: ^11.3.1
  cloudinary: ^1.2.0
  fbroadcast: ^2.0.0
  socket_io_client: ^3.0.2
  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/gosharp_icon.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icons/
    - assets/imgs/
    - assets/json/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Variable.ttf
        - asset: assets/fonts/Satoshi-VariableItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          style: italic
          weight: 900