name: gorider
description: "Rider App For Go Sharp Sharp LTD."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.1+3

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_image_compress: ^2.4.0
  skeletonizer: ^2.0.0
  dotted_border: ^2.1.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  upgrader:
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.4.0
  dotted_line: ^3.2.3
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player:
  lottie: ^3.1.3
  pinput: ^5.0.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.0
  fl_chart: ^0.69.0
  get_it: ^8.2.0
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.2
  flutter_google_maps_webservices: ^1.1.1
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  image_cropper: ^8.0.0
  intl_phone_field: ^3.1.0
  flutter_polyline_points: ^3.0.1
  cloudinary: ^1.2.0
  socket_io_client: ^3.0.2
  flutter_native_splash: ^2.4.0
  intl:
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  wakelock_plus: ^1.2.8
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - assets/svgs/
    - assets/icons/
    - assets/imgs/
    - assets/json/


  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  color: "#000000"
  image: "assets/icons/gorider-logo.png"
  android: true
  ios: true
  ios_content_mode: scaleAspectFit
  web: false
  android_12:
    color: "#000000"
    image: "assets/icons/gorider-logo-android.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/gorider-logo.png"

dependency_overrides:
  floating: ^6.0.0
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^3.1.4
  file_picker: 8.3.1
